swagger: "2.0"
info:
  description: Swagger file
  version: "1.0.0"
  title: Swagger ReST ServiceDesk
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /tickets:
    get:
      operationId: serviceDesk.read_all
      tags:
        - Chamados
      summary: Lista de Chamados
      description: Lista de Chamados
      responses:
        200:
          description: Sucesso na leitura de Chamados
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                description:
                  type: string
                user:
                  type: string


    post:
      operationId: serviceDesk.create
      tags:
        - Chamados
      summary: Cria um chamado e adiciona na lista de Chamados
      description: Adiciona na lista de Chamados
      parameters:
        - name: ticket
          in: body
          description: Chamado a ser criado
          required: True
          schema:
            type: object
            properties:
              title:
                type: string
                description: Titulo do chamado
              description:
                type: string
                description: Descricao do chamado
              user:
                type: string
                description: Usuario do chamado
      responses:
        201:
          description: Sucesso ao criar o chamado
  
  /tickets/{title}:
    put:
      operationId: serviceDesk.update
      tags:
        - Chamados
      summary: Update na lista de Chamados
      description: Update na lista
      parameters:
        - name: title
          in: path
          description: Titulo do chamado
          type: string
          required: True
        - name: ticket
          in: body
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              user:
                type: string
      responses:
        200:
          description: Sucesso ao atualizar o chamado

    delete:
      operationId: serviceDesk.delete
      tags:
        - Chamados
      summary: Deletar um chamado na lista de Chamados
      description: Deleta uma chamados
      parameters:
        - name: title
          in: path
          type: string
          required: True
      responses:
        200:
          description: Sucesso ao deletar o chamado
